# SELECT CASE WHEN DATA_FORMAT(DIFFERENTIATION_DATE, %C) 
# FROM ECOLI_DATA
# WHERE
SELECT QUARTER, COUNT(*) AS ECOLI_COUNT
FROM(
        SELECT *, CASE 
                    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%c') IN (1,2,3) THEN '1Q' 
                    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%c') IN (4,5,6) THEN '2Q'
                    WHEN DATE_FORMAT(DIFFERENTIATION_DATE, '%c') IN (7,8,9) THEN '3Q'
                    ELSE '4Q' 
                   END AS QUARTER
        FROM ECOLI_DATA
    ) AS SUB
GROUP BY QUARTER
ORDER BY QUARTER
;