# SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%M-%D') AS DATE_OF_BIRTH
# FROM MEMBER_PROFILE
# WHERE DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') LIKE '%-03-%'
# AND GENDER = 'W'
# AND TLNO IS NOT NULL
# ORDER BY MEMBER_ID 
# ;

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS date_of_birth
FROM MEMBER_PROFILE
WHERE GENDER = 'W'
  AND DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') LIKE '%-03-%'
  AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;