SELECT B.ID, C.FISH_NAME, B.LENGTH
FROM FISH_INFO B
INNER JOIN FISH_NAME_INFO C
ON B.FISH_TYPE = C.FISH_TYPE
WHERE B.LENGTH = (
    SELECT MAX(A.LENGTH)
    FROM FISH_INFO A
    WHERE A.FISH_TYPE = B.FISH_TYPE
)
;