SELECT 
        COUNT(*) AS FISH_COUNT, 
        MAX(A.LENGTH) AS MAX_LENGTH, 
        A.FISH_TYPE
FROM FISH_INFO A
LEFT JOIN 
    (
        SELECT FISH_TYPE
        FROM FISH_INFO
        GROUP BY FISH_TYPE
        HAVING AVG(CASE WHEN LENGTH <= 10 OR LENGTH IS NULL THEN 10 ELSE LENGTH END) >= 33
    ) B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_TYPE IS NOT NULL
GROUP BY A.FISH_TYPE
ORDER BY A.FISH_TYPE
;